import { z } from 'zod'

// validation using zod
/**
 *  1. id is not required -- because id will be gererated automatically in the backend
 *  2. password will be generated by "admin" or may generae automatically
 *  3.
 *
 */

const userValidationSchema = z.object({
  //  id: z.string(),
  password: z
    .string({
      invalid_type_error: 'Password must be string!!!',
    })
    .max(20, { message: 'Password can not be more than 20 charecters' })
    .optional(),
})

export const UserValidation = {
  userValidationSchema,
}
